Repository YanaSota/kaitaishinsho, pull requests merged in 2023-12, with the labels that each got.

#11 aa-enabled
  kawai/aa-enabled.md
  kawai/simonn_cmd.txt
Labels: wontfix

#10 aa-status
  kawai/aa-status.md
  kawai/simonn_cmd.txt
Labels: 修正お願いします！

#13 dmesgのみ
  yanagi/dir.md
  yanagi/dmesg.md
  yanagi/dmidecode.md
  yanagi/dnsdomainname.md
  テンプレ.md
Labels: 修正お願いします！

#14 pstarコマンドの完成
  nakanishi/ptar.md
Labels: 修正お願いします！

#36 py3compileの完成
  nakanishi/py3compile.md
Labels: 修正お願いします！, マージ未許可

#34 pwdxの完成
  nakanishi/pwdx.md
Labels: 修正お願いします！, マージ未許可

#35 pwunconvの完成
  nakanishi/pwunconv.md
Labels: 修正お願いします！, マージ未許可

#33 pwconvの完成
  nakanishi/pwconv.md
Labels: 修正お願いします！, マージ未許可, 修正しました！

#52 pydoc3の完成
  nakanishi/pydoc3.md
Labels: 修正しました！
