Repository YanaSota/kaitaishinsho, pull requests merged in 2024-01, with the labels that each got.

#48 dumpkeysの作成
  yanagi/dumpkeys.md
Labels: 修正お願いします！, 修正しました！

#50 （書籍版）ls
  tamura/ls.md
  tamura/ls_rm.md
Labels: 修正しました！

#49 chown 確認お願いします
  kitagawa/chown.md
Labels: 修正お願いします！, 修正しました！

#64 pzstdの完成
  nakanishi/pzstd.md
Labels: 修正お願いします！, 修正しました！

#39 chmod
  kitagawa/chmod.md
Labels: 修正お願いします！, マージ未許可, 修正しました！

#44 diffの詳細です
  goto/diff.md
Labels: 修正お願いします！, マージ未許可, 修正しました！

#45 cdコマンドの書籍版完成
  nakanishi/cd_in_print.md
Labels: 修正お願いします！, マージ未許可, 修正しました！

#47 Merge pull request #36 from YanaSota/py3compile
  goto/tr.md
Labels: 修正お願いします！, マージ未許可, 修正しました！

#68 rbashコマンドの完成
  nakanishi/rbash.md
Labels: 修正お願いします！, 修正しました！

#60 python3書籍版の完成
  nakanishi/python3_in_print.md
Labels: 修正お願いします！, マージ未許可, 修正しました！

#83 e2freefragの修正版
  yanagi/e2freefrag.md
Labels: 修正しました！
